### PR TITLE
Adding CreatedDate default value to Now()

### PR DESCRIPTION
**Pull request by Skrypt**
When creating a new Shipment so that we get proper Date displayed in admin UI.

sans titre-1

### CODE REVIEW

**Comment by asvishnyakov** [comment]
CreatedDate must be automatically initialized as DateTime.Now() via special [AuditableInterceptor](https://github.com/VirtoCommerce/vc-platform/blob/master/VirtoCommerce.Platform.Data/Infrastructure/Interceptors/AuditableInterceptor.cs). Why you need to do that?

**Comment by Skrypt** [comment]
The date gets saved properly as Datetime.Now but on the admin UI it displays a different Date than this.

**Comment by asvishnyakov** [comment]
@Skrypt In admin UI all dates and time displayed in timezone specified in user profile (current browser timezone by default). If you want to see all dates and time in UTC, just change timezone in your user profile.

**Comment by Skrypt** [comment]
I don't think it's related to TimeZones

**Comment by asvishnyakov** [comment]
@Skrypt What's date appear in admin and what's saved really? May you paste an example comparison?

**Comment by Skrypt** [comment]
If I go to the Demo Virto website and I create a new Shipment it will display 30 december 0 ... 
image
when I save it ...

image

I get DateTime.Now saved. So it's just a matter of displaying what is saved ...

**Comment by asvishnyakov** [comment]
As I can see, date after save is displayed correctly, right? And you worry only about 30 december 0... So it looks like just incorrect rendering on null date

**Comment by asvishnyakov** [comment]
From field must be empty on shipment creation, but is not, because we create new shipment on server. It is an architecture bug, so I created issue #14 for that. Current, you can don't worry about that and just ignore date in From field on shipment creation - it will be correctly filled (both in server and client side) on Order save.

Thank you very much for your feedback! We will fix this issues as soon as possible.

**Pull request closed without merging**
