### PR TITLE
Reviewed code on method GetInvoicePdf

### PR DESCRIPTION
**Pull request by miguelhasse**
Throw if order not found, and assume GetNewNotification always returns a Notification object (it will throw otherwise).

### CODE REVIEW

**Comment by tatarincev** [comment]
Could you make same PR to **dev** branch?

**Comment by Woland2k** [comment]
why not just merge it into master and then merge it to dev?

**Comment by tatarincev** [comment]
Then I'll lose sight of all the changes at merge dev -> master

**Comment by Woland2k** [comment]
Not sure I understand, don't think that is a lot of changes.

**Comment by miguelhasse** [comment]
@tatarincev I'm going to create a PR to the Dev branch (with build fix)

**Pull request closed without merging**
