### PR TITLE
Allow unregistering of notification types.

### PR DESCRIPTION
**Pull request by vanzegbroecke**

### CODE REVIEW

**Comment by vanzegbroecke** [comment]
@tatarincev I am fully aware that the IsActive flag would be a better solution, but for that I'm waiting for your update of the platform module (in which I hope this will be solved). But if we don't have the changes above, SetNotificationsParameters is called in the OrderNotificationObserver,  which then tries to set properties on a notfiication while that notification is null...

**Comment by tatarincev** [comment]
I'll soon make changes to the dev branch, and you will not need  longer your modification in the Order module related to disable the notifications working without exceptions

**Comment by tatarincev** [comment]
Please look at this commit https://github.com/VirtoCommerce/vc-platform/commit/90842d6643b2c6fc6c907018372d7e7613a67e5b 
These changes will no longer be required, you can leave all  this observer logic  unchmaged

**Comment by vanzegbroecke** [comment]
@tatarincev  Alright, that looks good!

**Comment by tatarincev** [comment]
Sorry I made mistake on conditions logic, I'll fix it in 5 min

**Comment by tatarincev** [comment]
Here you are 
https://github.com/VirtoCommerce/vc-platform/commit/3d83868b27f079374fd53f26becce57517e45f87

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-platform/releases/edit/v2.13.24

**Pull request closed without merging**
