### PR TITLE
Support http get for post processing with same logic as http post.

### PR DESCRIPTION
**Pull request by vanzegbroecke**
Http get is needed for Ogone/Ingenico payment method.

### CODE REVIEW

**Comment by artem-dudarev** [comment]
I think GET-requests must read data, not update it.

**Comment by vanzegbroecke** [comment]
Agreed, but I can't change the fact that this is how Ogone/Ingenico sends feedback, and there may be other payment methods that are implemented like that.

**Comment by tatarincev** [comment]
Initially, this method was not intended to be invoked by external clients of such payment services, it was assumed that only the storefront would call this method inside the callbacks on its side.

**Comment by vanzegbroecke** [comment]
The comment above the method says "Payment callback operation used by external payment services to inform post process payment in our system". Isn't that exactly what I'm doing?

**Comment by tatarincev** [comment]
Yes, the comment is correct, you won :)
But we need to  restricted of calling this method by additional permissions because this API method will be public and  it doesn't have any Authorization attributes except one 'security:call_api' assigned by default to each API method.
And please note that to use the platform API as a callback URL, you will need to take care of generating credentials (account and access key) for external payment service clients, In order they to be able to use these methods.
But from my point of view, definition these callback API on storefront looks more reasonable.

**Comment by vanzegbroecke** [comment]
@tatarincev The payment method uses a hash secret as a security measure.
I will do the callback from the storefront as you suggest, like we did before. I was just trying to integrate with Virto in a similar way as I could find as was done previously (cfr. POST method). So, in my opinion, that post method should also move to the storefront. If that's already coming from the storefront, then it's just the comment that's wrong and misleading. Thanks anyway. :)

**Comment by tatarincev** [comment]
Yes, I agree, the comment should be edited and not contain any information about the use of external clients.

**Pull request closed without merging**
